### ISSUE TITLE
Telemetry copyover socket accessor breaks Ubuntu MySQL client build

### ISSUE THREAD

**Issue by xander-l** [Community-Duris/Duris#385]
## Bug

The MySQL-backed build on Ubuntu 24.04 fails after #384 because sql_open_telemetry_connection() calls mysql_get_socket(). That function is declared by MariaDB Connector/C, but not by the Oracle MySQL client headers installed by the repository's duris-build-deps package.

Failed current-master merge-ref job: https://github.com/Community-Duris/Duris/actions/runs/34922635081/job/104233955033

```text
src/sql/sql.c:1134:41: error: ‘mysql_get_socket’ was not declared in this scope
```

## Impact

- The required compile test / build check is red for PRs tested against current master.
- A clean Ubuntu 24.04 MySQL-backed server build cannot complete with the supported client development package.
- The copyover close-on-exec guarantee must remain intact; deleting the descriptor setup could leave the telemetry writer connection and advisory lock inherited by the replacement process.

## Investigation

Four approaches were checked:

1. Remove or skip FD_CLOEXEC: rejected because it reintroduces the copyover lock/socket leak #384 prevents.
2. Stop the telemetry worker before exec: rejected because copyover intentionally performs a bounded flush and must resume the existing worker if exec fails; this would require a broader restart/state-recovery protocol.
3. Use mysql_get_socket_descriptor() from upstream mysql_async.h: rejected after testing the exact Ubuntu 24.04 libmysqlclient-dev package. It ships neither that header nor that exported symbol.
4. Isolate the installed-client distinction behind one internal compatibility boundary: use MariaDB's named mysql_get_socket() accessor and, for Oracle libmysqlclient, the MYSQL.net.fd ABI field its installed public headers retain and annotate for external DBI integrations.

Option 4 is the narrowest correct repair. It preserves failed-exec behavior and FD_CLOEXEC, contains the ABI dependency in one auditable header, has no runtime branch, and can be compiled against both exact installed header families.

## Acceptance criteria

- MariaDB Connector/C builds continue to compile and set FD_CLOEXEC.
- Ubuntu 24.04's Oracle MySQL client headers compile using their installed MYSQL/NET ABI.
- The complete Ubuntu build check passes without weakening telemetry connection or copyover behavior.
- Compile contracts cover MariaDB, Oracle, and the client headers installed on the executing host.

**Comment by xander-l** [comment]
Resolved by merged PR #383. That change replaces the MariaDB-only mysql_get_socket call with a client-selected sql_telemetry_socket boundary, compiles against Oracle MySQL and MariaDB client shapes, and verifies FD_CLOEXEC plus advisory-lock release across exec. PR #387 was independently developed for this issue but is now closed as a duplicate.
